jwt:
  start: Bearer
  accessHeader: X-access-token
  accessExpiration: 1800
  refreshHeader: X-refresh-token
  refreshExpiration: 604800
#  secret: ENC(SMGyv0QaAfFvFBlTAH1T/Q==)
  key:
    public: rsakey/public.key
    private: rsakey/private.key
server:
  port: 8280
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backend?serverTimezone=GMT%2B8
    username: root
    password: ENC(DDuWH3B+9JCi7IVVMiD+OQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 10
      min-idle: 1
      filters: stat, wall, log4j2
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
          db-type: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 192.168.17.128
    database: 0
    port: 6379
    timeout: 1000
    password:
jasypt:
  encryptor:
    password: akashiro